config/routes.rb
Base::Application.routes.draw do
  mount Interpret::Engine => "/admin/interpret"

  # Backoffice
  namespace :admin do
    resources :users, only: [:index, :new, :create, :destroy]
    resources :translations, :only => [:index, :create] do
      get :other_langs, :on => :member
      get :missing, :on => :collection
      get :tools, :on => :collection
      get :export, :on => :collection
      post :import, :on => :collection
    end

    root to: 'users#index'
  end

  scope ":i18n_locale" do
    localized(LOCALES_STRING) do
      resources :sessions, only: [:new, :create, :destroy]
      resources :password_resets, only: [:new, :create, :edit, :update]
    end

    # Sessions
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'login' => 'sessions#new', as: 'login'

    root to: 'static#index'
  end

  match '/' => 'static#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:notice] = t('user_created', scope: 'flashes.users_controller')
      redirect_to admin_users_path
    else
      flash[:error] = t('creation_error', scope: 'flashes.users_controller')
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])

    if User.count <= 1 || @user == current_user
      flash[:error] = t('deletion_error', scope: 'flashes.users_controller')
      redirect_to :back
    else
      @user.destroy
      flash[:notice] = t('user_deleted', scope: 'flashes.users_controller')
      redirect_to admin_users_path
    end
  end
end

app/views/admin/users/_header.html.slim
= render 'submenu'

h1.page-header
  =' t('title', scope: 'users')
  - if defined? subtitle
    small= subtitle

  = yield :actions

app/views/admin/users/_submenu.html.slim
- content_for :submenu do
  = navigation_item_for(admin_users_path, admin_root_path) do
    = link_to t('all_users', scope: 'users'), admin_users_path
  = navigation_item_for(new_admin_user_path) do
    = link_to t('create_user', scope: 'users'), new_admin_user_path

app/views/admin/users/index.html.slim
- content_for :actions do
  = link_to t('create_user', scope: 'users'), new_admin_user_path, class: "btn btn-success pull-right"

= render 'header'

- if @users.any?
  table.table.table-striped
    thead
      tr
        th Email
        th
    tbody
      - @users.each do |user|
        tr
          td= user.email
          td
            = link_to t('delete', scope: 'actions'), [:admin, user], confirm: t('you_sure', scope: 'actions'), :method => :delete, class: "btn btn-danger pull-right"
- else
  .well
    = t('.no_users')

app/views/admin/users/new.html.slim
= render 'header', subtitle: t('create_user', scope: 'users')

= simple_form_for [:admin, @user], defaults: { wrapper: :with_controls, label_html: { class: 'form--horizontal__control-label' } } do |f|
  = f.input :email
  = f.input :password, label: t('password', scope: 'users.fields')
  = f.input :password_confirmation, label: t('password_confirmation', scope: 'users.fields')
  = f.button :submit