config/routes.rb
Base::Application.routes.draw do
  mount Interpret::Engine => "/admin/interpret"

  # Backoffice
  namespace :admin do
    resources :users, only: [:index, :new, :create, :destroy]
    resources :translations, :only => [:index, :create] do
      get :other_langs, :on => :member
      get :missing, :on => :collection
      get :tools, :on => :collection
      get :export, :on => :collection
      post :import, :on => :collection
    end

    root to: 'users#index'
  end

  scope ":i18n_locale" do
    localized(LOCALES_STRING) do
      resources :sessions, only: [:new, :create, :destroy]
      resources :password_resets, only: [:new, :create, :edit, :update]
    end

    # Sessions
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'login' => 'sessions#new', as: 'login'

    root to: 'static#index'
  end

  match '/' => 'static#index'
end

app/controllers/admin/translations_controller.rb
# encoding: utf-8

require 'csv'

class Admin::TranslationsController < Admin::ApplicationController
  def index
    @translations = Interpret::Translation.scoped
    @search_params = Hash["key" => "", "value" => "", "language" => "All"]

    if params[:search].present?
      @search_params = params[:search]
      t = Interpret::Translation.arel_table
      @translations = @translations.where(t[:key].
        matches("%#{params[:search][:key]}%").
        and(t[:value].matches("%#{params[:search][:value]}%")))
      if LOCALES.include?(params[:search][:language].to_sym)
        @translations = @translations.where(t[:locale].eq("#{params[:search][:language]}"))
      end
    end

    @translations = @translations.order('translations.key').paginate(:page => params[:page], :per_page => 20)
  end

  def create
    @translation = Interpret::Translation.new(params[:translation])

    if @translation.save
      flash[:notice] = t('new_translation', scope: 'flashes.translations_controller', key: @translation.key)
      redirect_to missing_admin_translations_url
    else
      flash[:alert] = t('error_creating_translation', scope: 'flashes.translations_controller')
      redirect_to missing_admin_translations_url
    end
  end

  def other_langs
    if @translation = Interpret::Translation.find(params[:id])
      @translations = Interpret::Translation.where('translations.key = ? AND translations.locale != ?', @translation.key, @translation.locale)
    end
    render :layout => false
  end

  def missing
    @missing_translations = get_missing_translations
    @translation = Interpret::Translation.new
  end

  def export
    locale = params[:locale].try(:to_sym)
    unless TRANSLATABLE_LOCALES.include?(locale)
      flash[:alert] = t('language_incorrect', scope: 'flashes.translations_controller')
      redirect_to admin_translations_url
    end

    all = params[:all] == 'true'
    translations = Interpret::Translation.where(:locale => I18n.default_locale.to_s)

    xls_file = CSV.generate(col_sep: "\t") do |csv|
      csv << ['Key', LANGUAGES_BY_LOCALE[I18n.default_locale.to_s], locale]
      translations.each do |translation|
        foreign_value = Interpret::Translation.where(:key => translation.key, :locale => locale).first.try(:value) || ""
        if all || foreign_value.blank?
          csv << [translation.key, translation.value, foreign_value]
        end
      end
    end

    respond_to do |format|
      format.xls do
        send_data xls_file.encode(Encoding::ISO_8859_1, :undef => :replace),
          :type => 'xls; charset=iso-8859-1; header=present',
          :disposition => "attachment; filename=translations_#{locale}.xls"
      end
    end
  end

  def import
    if params.include?(:import) && file = params[:import][:file]
      file = params[:import][:file]
      locale = params[:import][:locale]

      keys = 0

      Interpret::Translation.transaction do
        xls = Roo::Excel.new(file.path, false, :ignore)
        (xls.first_row+1..xls.last_row).each do |i|
          key = xls.cell(i, 1)
          in_foreign_language = xls.cell(i, 3)

          translation = Interpret::Translation.find_or_create_by_locale_and_key(locale, key)
          if in_foreign_language.present? && translation.value != in_foreign_language
            translation.update_attribute(:value, in_foreign_language)
            keys += 1
          end
        end
      end

      redirect_to admin_translations_url, :notice => t('translations_imported', scope: 'flashes.translations_controller', num_of_keys: keys)
    else
      redirect_to admin_translations_url, :alert => t('attach_file', scope: 'flashes.translations_controller')
    end
  end

  private

  def get_missing_translations
    missing_translations = Hash.new []

    Interpret::Translation.all.group_by(&:key).each do |key, translations|
      if base = translations.find{|ta| ta['locale'] == I18n.default_locale.to_s }
        (TRANSLATABLE_LOCALES - translations.map { |t| t.locale.to_sym }).each do |missing_locale|
           missing_translations[missing_locale] = missing_translations[missing_locale] << {:key => key, :base_value => base['value']}
        end
      end
    end
    missing_translations
  end
end

app/views/admin/translations/_header.html.slim
= render 'submenu'

#translations-header
  = yield :actions

  h1.page-header
    = t('title', scope: 'admin.translations')

app/views/admin/translations/_submenu.html.slim
- content_for :submenu do
  = navigation_item_for(admin_translations_path) do
    = link_to t('list', scope: 'admin.translations'), admin_translations_path
  = navigation_item_for(missing_admin_translations_path) do
    = link_to t('missing_link', scope: 'admin.translations'), missing_admin_translations_path
  = navigation_item_for(tools_admin_translations_path) do
    = link_to t('tools_link', scope: 'admin.translations'), tools_admin_translations_path

app/views/admin/translations/_translations_table.html.slim
table.table.table-striped
  thead
    th= t('language', scope: 'admin.translations')
    th= t('key', scope: 'admin.translations')
    th= t('value', scope: 'admin.translations')
    - if with_other
      th
  tbody
    - translations.each do |t|
      tr
        td= LANGUAGES_BY_LOCALE[t.locale]
        td= t.key
        td= best_in_place t, :value, :type => :textarea, :path => interpret.translation_url(t.locale, t.id), :sanitize => false
        - if with_other
          td
            = link_to "+", other_langs_admin_translation_url(t.id), :class => 'other_langs btn', :remote => true

app/views/admin/translations/index.html.slim
- content_for :actions do
  .info.pull-right
    #language-form.pull-right
      = simple_form_for :search, :url => admin_translations_url, :method => :get do |f|
        = f.hidden_field :key, :value => @search_params[:key]
        = f.hidden_field :value, :value => @search_params[:value]
        = f.input :language, :collection => [[t('.all_languages'),'tots']].concat(LANGUAGES), :include_blank => false, :selected => @search_params[:language], :label => false, :input_html => {:class => 'submit-on-change input-medium'}
    h4#results.pull-right
      =' @translations.total_entries
      = t('.results')

= render 'header'

#search-form
  = simple_form_for :search, :url => admin_translations_path, :method => :get do |f|
    = f.hidden_field :language, :value => @search_params['language']
    = f.input :key, :as => :string, :label => t('key', scope: 'admin.translations'), :required => false, :input_html => { :value => @search_params[:key], :class => 'input-medium' }
    = f.input :value, :as => :string, :label => t('value', scope: 'admin.translations'), :required => false,  :input_html => { :value => @search_params[:value], :class => 'input-large' }
    = f.button :submit, t('.search')

- if @translations.any?
  #translations-table
    = will_paginate @translations
    = render 'translations_table', :translations => @translations, :with_other => true
    = will_paginate @translations
- else
  .leader.well= t('no_results')

#translations-modal.modal.hide.fade
  .modal-header
    button.close data-dismiss="modal" x
    h3= t('.other_languages')
  .modal-body

- content_for :custom_js do
  javascript:
    $(document).ready(
      function(){
        $("a.other_langs").bind("ajax:success",
          function(evt, data, status, xhr){
            $("#translations-modal .modal-body").html(data);
            $("#translations-modal").modal();
          }).bind("ajax:error",
          function(evt, data, status, xhr){
            console.log('error retrieving data')
          });
    });

app/views/admin/translations/missing.html.slim
= render 'header'

#translations-missing-list
  - if @missing_translations.any?
    - @missing_translations.each do |locale, translations|
      - if translations.any?
        table.table
          thead
            th= t('language', scope: 'admin.translations')
            th= t('key', scope: 'admin.translations')
            th
              =' t('.value_in')
              = LANGUAGES_BY_LOCALE[I18n.default_locale.to_s]
            th= t('.new_value')
            th
          tbody
            - translations.each do |translation|
              tr
                = simple_form_for [:admin, @translation], :method => :post do |f|
                  = f.hidden_field :locale, :value => locale
                  = f.hidden_field :key, :value => translation[:key]
                  td= LANGUAGES_BY_LOCALE[locale.to_s]
                  td= translation[:key]
                  td= translation[:base_value]
                  td= f.input :value, :as => :string, :label => false
                  td= f.button :submit, t('create', scope: 'actions')
  - else
    .leader.well Everything translated! No results to show

app/views/admin/translations/other_langs.html.slim
= render 'translations_table', :translations => @translations, :with_other => false

app/views/admin/translations/tools.html.slim
= render 'header'

h2.page-header= t('.export')
table.table.table-striped
  - TRANSLATABLE_LOCALES.each do |locale|
    tr
      td= LANGUAGES_BY_LOCALE[locale.to_s]
      td
        = link_to t('.download_all'), export_admin_translations_url(:locale => locale, :all => true, :format => :xls), :class => "btn btn-mini btn-primary"
        = link_to t('.download_pending'), export_admin_translations_url(:locale => locale, :all => false, :format => :xls), :class => "btn btn-mini btn-warning"

h2.page-header= t('.import')
table.table.table-striped
  .alert
    = link_to "x", "#", :class => :close, "data-dismiss" => :alert
    p= t('.dangerous_action')

  - TRANSLATABLE_LOCALES.each do |locale|
    tr
      td= LANGUAGES_BY_LOCALE[locale.to_s]
      td
        = simple_form_for :import, :url => import_admin_translations_url do |f|
          = f.input :file, :as => :file, :label => false
          = f.input :locale, :as => :hidden, :input_html => { :value => locale }

- content_for :custom_js do
  javascript:
    $("input[type=file]").change(function(){
      $(this).before(t('.loading_file'));
      $(this).parent().parent().submit();
      $(this).remove();
    });