config/routes.rb
Base::Application.routes.draw do
  mount Interpret::Engine => "/admin/interpret"

  # Backoffice
  namespace :admin do
    resources :users, only: [:index, :new, :create, :destroy]
    resources :translations, :only => [:index, :create] do
      get :other_langs, :on => :member
      get :missing, :on => :collection
      get :tools, :on => :collection
      get :export, :on => :collection
      post :import, :on => :collection
    end

    root to: 'users#index'
  end

  scope ":i18n_locale" do
    localized(LOCALES_STRING) do
      resources :sessions, only: [:new, :create, :destroy]
      resources :password_resets, only: [:new, :create, :edit, :update]
    end

    # Sessions
    get 'logout' => 'sessions#destroy', as: 'logout'
    get 'login' => 'sessions#new', as: 'login'

    root to: 'static#index'
  end

  match '/' => 'static#index'
end

app/views/admin/shared/_alert.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name == :notice ? "success" : "error"}"
      = link_to "×", "#", :class => "close", "data-dismiss" => "alert"
      div id="flash_#{name}" = msg

app/views/admin/shared/_menu.html.slim
#admin_menu.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "Base", admin_root_path, :class => 'brand'
      - if current_user
        ul.nav
          li= activable_link_to "Users", admin_users_path
          li= activable_link_to "Translations", admin_translations_path
      ul.nav.pull-right
        - if logged_in?
          li.name= current_user.email
          li= link_to t('logout', scope: 'actions'), logout_path(:i18n_locale => I18n.locale)

app/views/admin/shared/_submenu.html.slim
.navbar.subnav-fixed
  .navbar-inner
    ul.nav
      = yield :submenu